language: python
python: 3.5
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  # - TOX_ENV=py36
  # - TOX_ENV=py37
matrix:
  include:
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "3.7"
      env: TOX_ENV=py37
      dist: xenial
      language: python
      sudo: required
install:
  - pip install tox
script:
  - tox -e 
sudo: false
